#!/bin/sh
TOP=/raid1/tomato/tomato.git/release.ar.wp.chs/src-rt/router
CONFIGURE="./configure"
CC=mipsel-linux-gcc
CXX=mipsel-linux-g++
AR=mipsel-linux-ar
RANLIB=mipsel-linux-ranlib

CC=$CC CXX=$CXX AR=$AR RANLIB=$RANLIB STRIP='mipsel-uclibc-strip' HOST=mipsel-linux \
	CFLAGS="-Wall -Os -D_GNU_SOURCE $EXTRACFLAGS -D_FILE_OFFSET_BITS=64 \
	-ffunction-sections -fdata-sections \
	-I$TOP/ffmpeg/libavutil -I$TOP/ffmpeg/libavcodec -I$TOP/ffmpeg/libavformat \
	-I$TOP/ffmpeg/libswscale -I$TOP/ffmpeg \
	-I$TOP/flac/include -I$TOP/sqlite -I$TOP/jpeg \
	-I$TOP/libexif -I$TOP/libid3tag -I$TOP/libogg/include \
	-I$TOP/libvorbis/include \
	-I$TOP/libiconv/include \
	-I$TOP/sqlite" \
	LDFLAGS="-ffunction-sections -fdata-sections -Wl,--gc-sections -fPIC \
	-L$TOP/zlib -L$TOP/sqlite/.libs -L$TOP/jpeg -L$TOP/libvorbis/lib/.libs \
	-L$TOP/libogg/src/.libs -L$TOP/libexif/libexif/.libs -L$TOP/flac/src/libFLAC/.libs \
	-L$TOP/ffmpeg/libavutil -L$TOP/ffmpeg/libavcodec -L$TOP/ffmpeg/libavformat \
	-L$TOP/libid3tag/.libs -L$TOP/libiconv/lib/.libs" \
	CPPFLAGS="-Wall -Os -D_GNU_SOURCE $EXTRACFLAGS -D_FILE_OFFSET_BITS=64 \
	-ffunction-sections -fdata-sections \
	-I$TOP/ffmpeg/libavutil -I$TOP/ffmpeg/libavcodec -I$TOP/ffmpeg/libavformat \
	-I$TOP/ffmpeg/libswscale -I$TOP/ffmpeg \
	-I$TOP/flac/include -I$TOP/sqlite -I$TOP/jpeg \
	-I$TOP/libexif -I$TOP/libid3tag -I$TOP/libogg/include \
	-I$TOP/libvorbis/include \
	-I$TOP/libiconv/include \
	-I$TOP/sqlite" \
	LIBS="-lpthread -lexif -ljpeg -lsqlite3 -lavformat -lavutil -lavcodec -lid3tag -lFLAC -logg -lvorbis -lm -ldl -lz" \
	$CONFIGURE --host=mipsel-linux --build=x86_64-linux-gnu

make
