#!/bin/sh

case "$1" in
  addcru)
   ISCRU=`cru l | grep aria2_inside | wc -l`

   INTERVAL=`nvram get aria2_check_time`

   BTON=`nvram get aria2_enable`
   if [ "$BTON" == "1" ]; then
    BTCH=`nvram get aria2_check`
    if [ "$BTCH" == "1" ]; then
     if [ "$ISCRU" == "0" ]; then
      cru a aria2_inside "*/$INTERVAL * * * * /usr/bin/archeck check"
     else
      cru d aria2_inside
      cru a aria2_inside "*/$INTERVAL * * * * /usr/bin/archeck check"
     fi
    else
     if [ "$ISCRU" == "1" ]; then
      cru d aria2_inside
     fi
    fi
   else
    if [ "$ISCRU" == "1" ]; then
      cru d aria2_inside
    fi
   fi
  ;;
  check)
   BTON=`nvram get aria2_enable`
   if [ "$BTON" == "1" ]; then
    BTCH=`nvram get aria2_check`
    if [ "$BTCH" == "1" ]; then
     ON=`ps w | grep aria2c | grep -v grep | wc -l`
     if [ "$ON" == "0" ]; then
      logger aria2c stopped? Starting...
      service aria2 restart
     fi
    fi
   fi
  ;;
esac
exit 0
