#!/bin/sh -e

mkdir -p bin

echo '#!/bin/sh' > bin/okabi
echo 'echo local' >> bin/okabi

exec < c
echo '#!/bin/sh' > bin/okc-local
while read compiler; do
  $compiler lib.c main.c -o test-c || continue
  echo "echo $compiler" >> bin/okc-local
done
 
echo '#!/bin/sh' > bin/okcpp-local

echo '#!/bin/sh' > bin/oklibs-local
echo 'echo "  -pie -Wl,-z,relro -Wl,-z,now -Wl,-z,noexecstack -L/usr/local/lib -ldl -lm "' >> bin/oklibs-local

echo '#!/bin/sh' > bin/okar-local
echo 'exec mipsel-uclibc-ar "$@"' >> bin/okar-local

chmod +x bin/ok*
