#line 2 "prsa_tok.c"

#line 4 "prsa_tok.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer prsa_create_buffer
#define yy_delete_buffer prsa_delete_buffer
#define yy_flex_debug prsa_flex_debug
#define yy_init_buffer prsa_init_buffer
#define yy_flush_buffer prsa_flush_buffer
#define yy_load_buffer_state prsa_load_buffer_state
#define yy_switch_to_buffer prsa_switch_to_buffer
#define yyin prsain
#define yyleng prsaleng
#define yylex prsalex
#define yylineno prsalineno
#define yyout prsaout
#define yyrestart prsarestart
#define yytext prsatext
#define yywrap prsawrap
#define yyalloc prsaalloc
#define yyrealloc prsarealloc
#define yyfree prsafree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE prsarestart(prsain  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t prsaleng;

extern FILE *prsain, *prsaout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up prsatext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up prsatext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via prsarestart()), so that the user can continue scanning by
	 * just pointing prsain at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when prsatext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t prsaleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow prsawrap()'s to do buffer switches
 * instead of setting up a fresh prsain.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void prsarestart (FILE *input_file  );
void prsa_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE prsa_create_buffer (FILE *file,int size  );
void prsa_delete_buffer (YY_BUFFER_STATE b  );
void prsa_flush_buffer (YY_BUFFER_STATE b  );
void prsapush_buffer_state (YY_BUFFER_STATE new_buffer  );
void prsapop_buffer_state (void );

static void prsaensure_buffer_stack (void );
static void prsa_load_buffer_state (void );
static void prsa_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER prsa_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE prsa_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE prsa_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE prsa_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *prsaalloc (yy_size_t  );
void *prsarealloc (void *,yy_size_t  );
void prsafree (void *  );

#define yy_new_buffer prsa_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        prsaensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            prsa_create_buffer(prsain,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        prsaensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            prsa_create_buffer(prsain,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *prsain = (FILE *) 0, *prsaout = (FILE *) 0;

typedef int yy_state_type;

extern int prsalineno;

int prsalineno = 1;

extern char *prsatext;
#define yytext_ptr prsatext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up prsatext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	prsaleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 25
#define YY_END_OF_BUFFER 26
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[194] =
    {   0,
       22,   22,   26,   25,   22,   23,   24,   17,   18,   18,
       18,   18,    3,   25,   25,   25,   25,   25,   25,   25,
        1,    2,   22,   24,    0,   18,   21,    0,    0,    0,
       18,   18,   18,   21,   21,   21,   21,   21,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       18,    0,   21,    8,    7,   18,    0,   21,   21,   21,
       21,   21,   21,   21,   21,   21,    0,    0,    0,    5,
        6,    0,    0,    4,   19,    0,    0,    0,    0,   18,
        0,    0,    0,    0,   21,   21,    0,   21,   21,   21,
       21,   21,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   18,    0,    0,    0,    0,   21,    0,    0,    0,
       21,   21,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   12,   13,    0,    0,   20,   20,   20,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    9,    0,
        0,   20,   20,   20,   21,   21,   21,    0,    0,    0,
        0,    0,    0,    0,    0,   21,   21,   21,   21,   21,
       21,    0,   14,   15,    0,    0,   21,   21,   21,    0,
        0,    0,   16,    0,    0,    0,    0,    0,    0,    0,
       10,   11,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    4,    1,    1,    1,    1,    1,
        1,    1,    5,    1,    1,    6,    7,    8,    9,   10,
       11,   11,   12,   13,   13,   13,   13,   14,    1,    1,
        5,    1,    1,    1,   15,   16,   17,   18,   19,   18,
        5,    5,    5,    5,   20,    5,   21,    5,    5,   22,
        5,   23,   24,    5,   25,    5,    5,    5,    5,    5,
        1,    1,    1,    1,    1,    1,   26,   27,   28,   29,

       30,   31,    5,    5,   32,    5,    5,   33,   34,   35,
       36,   37,    5,   38,   39,   40,   41,   42,    5,   43,
       44,    5,   45,    1,   46,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    1,    3,    4,    3,    5,    5,    5,
        5,    5,    5,    6,    7,    7,    7,    7,    7,    3,
        3,    3,    3,    3,    3,    7,    7,    7,    7,    7,
        7,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    1,    1
    } ;

static yyconst flex_int16_t yy_base[213] =
    {   0,
        0,    0,  674,  675,  671,  675,    0,  675,   41,   22,
       77,   65,  113,  122,  636,  628,  634,   54,  645,  633,
      675,  675,  665,    0,   88,  130,  154,  163,    0,    0,
        0,  653,   94,  171,  100,  142,  195,  204,  635,  627,
      634,  642,  645,  628,  632,  643,  613,  650,  212,  649,
      220,  246,    0,    0,    0,  648,  183,  254,  280,    0,
      640,  646,  288,  232,  266,  314,  620,  614,  608,  675,
      675,   49,  615,  675,  675,  300,  641,  322,  640,  631,
      630,  637,  329,  636,  123,  164,  335,  343,  369,    0,
      628,  634,  608,  603,  604,  606,  609,  602,  627,  377,

      626,  355,  383,  625,  391,  624,  615,  622,  398,  621,
      205,  247,  594,  595,  583,   53,  583,  594,  404,  615,
      412,  614,  613,  419,  612,  425,  577,  433,  574,  550,
      533,  482,  675,  675,  448,  452,  438,  444,  450,  456,
      434,  464,  420,  413,  471,  399,  366,  344,  675,  357,
      307,  477,  483,  675,  488,  494,  500,  506,  330,  514,
      323,  291,   72,  252,  250,  519,  525,  675,  530,  536,
      542,  244,  675,  675,  190,  119,  548,  554,  675,   79,
       82,   82,  675,   80,   84,   64,   58,   31,   24,    8,
      675,  675,  675,  566,  569,  574,  577,  580,  584,  586,

      587,  590,  592,  594,  598,  600,  602,  604,  606,  608,
      610,  612
    } ;

static yyconst flex_int16_t yy_def[213] =
    {   0,
      193,    1,  193,  193,  193,  193,  194,  193,  193,    9,
        9,   11,  195,   11,   14,   14,  193,  193,  193,   14,
      193,  193,  193,  194,  193,  193,  195,   26,  196,  197,
       26,   26,   26,  193,   34,   35,  198,   35,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  199,  193,  200,
      193,   51,   27,  196,  197,   51,  193,  193,   58,   58,
       58,   59,  193,   63,   64,   64,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  200,  193,  193,  201,
      193,  202,  193,  203,  204,  204,  193,  193,   88,   88,
       88,   89,  193,  193,  193,  193,  193,  193,  205,  193,

      206,  193,  193,  203,  193,  193,  193,  207,  193,  208,
      204,  204,  193,  193,  193,  193,  193,  193,  193,  206,
      193,  193,  209,  193,  210,  193,  208,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      210,  193,  193,  211,  193,  212,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  212,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,    0,  193,  193,  193,  193,  193,  193,  193,

      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193
    } ;

static yyconst flex_int16_t yy_nxt[722] =
    {   0,
        4,    5,    6,    7,    4,    4,    8,    9,   10,   11,
       12,   12,   12,   13,   14,   14,   15,   14,   16,    4,
       17,   18,   19,    4,    4,   20,   14,   14,   14,   14,
       14,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,   21,   22,   25,  192,   26,   26,
       26,   26,   26,   26,   27,   28,   28,   28,   28,   28,
      193,  133,  134,  191,  193,  190,   28,   28,   28,   28,
       28,   28,   33,   33,   33,   33,   33,   42,   43,   29,
      173,  174,   96,   30,   31,   31,   31,   31,   32,   33,
       97,   44,  189,  188,   45,   48,   48,   49,   50,   50,

       50,   56,   56,   56,   56,   56,   56,   60,   60,   60,
       60,   61,   62,  187,  186,  193,  185,  184,  183,  193,
       34,   34,   35,   36,   36,   36,   37,  193,   57,   28,
       28,   28,   28,   28,   28,   25,   27,   51,   51,   51,
       51,   51,   51,   27,   52,   52,   52,   52,   52,   62,
       62,   62,   62,   62,  182,   52,   52,   52,   52,   52,
       52,   34,   34,   35,   36,   36,   36,   53,  193,  193,
       52,   52,   52,   52,   52,   52,   57,   27,   58,   58,
       58,   58,   58,   58,   27,   59,   59,   59,   59,   59,
       82,   82,   83,   84,   84,   84,   59,   59,   59,   59,

       59,   59,   63,   63,   64,   65,   65,   65,   53,  193,
       87,   59,   59,   59,   59,   59,   59,   76,   27,   77,
       77,   77,   77,   78,   79,   25,  181,   80,   80,   80,
       80,   80,   80,   27,   81,   81,   81,   81,   81,   90,
       90,   90,   90,   91,   92,   81,   81,   81,   81,   81,
       81,  193,  193,   81,   81,   81,   81,   81,   81,   57,
       27,   85,   85,   85,   85,   85,   85,   27,   86,   86,
       86,   86,   86,   92,   92,   92,   92,   92,  180,   86,
       86,   86,   86,   86,   86,  193,  176,   86,   86,   86,
       86,   86,   86,   87,  175,   88,   88,   88,   88,   88,

       88,   27,   89,   89,   89,   89,   89,   99,   99,  100,
      101,  101,  101,   89,   89,   89,   89,   89,   89,  193,
      172,   89,   89,   89,   89,   89,   89,   76,  158,   79,
       79,   79,   79,   79,  103,  158,  104,  104,  104,  104,
      105,  106,  108,  108,  109,  110,  110,  110,   87,  165,
      111,  111,  111,  111,  111,  111,   27,  112,  112,  112,
      112,  112,  102,  102,  102,  102,  102,  102,  112,  112,
      112,  112,  112,  112,  193,  164,  112,  112,  112,  112,
      112,  112,  119,  163,  120,  120,  120,  120,  121,  122,
      123,  123,  124,  125,  125,  125,  103,  162,  106,  106,

      106,  106,  106,  126,  158,  127,  127,  127,  127,  128,
      129,  137,  137,  138,  139,  139,  139,  119,  158,  122,
      122,  122,  122,  122,  140,  140,  141,  141,  141,  141,
      142,  143,  144,  144,  145,  146,  146,  146,  126,  140,
      129,  129,  129,  129,  129,  139,  139,  139,  139,  139,
      139,  152,  152,  152,  152,  153,  154,  154,  154,  154,
      154,  154,  154,  155,  155,  156,  157,  157,  157,  140,
      151,  143,  143,  143,  143,  143,  158,  150,  159,  159,
      159,  159,  160,  161,  154,  154,  154,  154,  154,  154,
      154,  154,  154,  154,  154,  157,  157,  157,  157,  157,

      157,  166,  166,  166,  166,  167,  168,  168,  168,  168,
      168,  168,  168,  169,  169,  170,  171,  171,  171,  158,
      149,  161,  161,  161,  161,  161,  168,  168,  168,  168,
      168,  168,  168,  168,  168,  168,  168,  171,  171,  171,
      171,  171,  171,  177,  177,  177,  177,  178,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      179,  179,  179,  179,  179,  179,   24,  148,   24,   24,
       24,   24,   24,   38,   38,   38,   54,  147,   54,  126,
       54,   55,  126,   55,   66,   66,   66,   50,   50,   79,
       79,  102,  102,   84,   84,  106,  106,  107,  107,  107,

      107,  101,  101,  122,  122,  110,  110,  129,  129,  125,
      125,  143,  143,  146,  146,  161,  161,  140,  140,  119,
      119,  136,  135,  132,  131,  130,  126,  126,   27,  103,
      103,  119,  119,  118,  117,  116,  115,  114,  113,   87,
      112,  103,  103,   27,   27,   76,   76,   98,   95,   94,
       93,   57,   86,  193,   76,   76,   75,   74,   73,   72,
       71,   70,   69,   68,   67,   56,   23,   47,   46,   41,
       40,   39,   23,  193,    3,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,

      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193
    } ;

static yyconst flex_int16_t yy_chk[722] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    9,  190,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
       10,  116,  116,  189,   10,  188,    9,    9,    9,    9,
        9,    9,   12,   12,   12,   12,   12,   18,   18,    9,
      163,  163,   72,    9,   11,   11,   11,   11,   11,   11,
       72,   18,  187,  186,   18,   25,   25,   25,   25,   25,

       25,   33,   33,   33,   33,   33,   33,   35,   35,   35,
       35,   35,   35,  185,  184,   11,  182,  181,  180,   11,
       13,   13,   13,   13,   13,   13,   13,   14,   85,   14,
       14,   14,   14,   14,   14,   26,   85,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   36,
       36,   36,   36,   36,  176,   26,   26,   26,   26,   26,
       26,   27,   27,   27,   27,   27,   27,   27,   28,   86,
       28,   28,   28,   28,   28,   28,   34,   86,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       57,   57,   57,   57,   57,   57,   34,   34,   34,   34,

       34,   34,   37,   37,   37,   37,   37,   37,   37,   38,
      111,   38,   38,   38,   38,   38,   38,   49,  111,   49,
       49,   49,   49,   49,   49,   51,  175,   51,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   64,
       64,   64,   64,   64,   64,   51,   51,   51,   51,   51,
       51,   52,  112,   52,   52,   52,   52,   52,   52,   58,
      112,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   65,   65,   65,   65,   65,  172,   58,
       58,   58,   58,   58,   58,   59,  165,   59,   59,   59,
       59,   59,   59,   63,  164,   63,   63,   63,   63,   63,

       63,   63,   63,   63,   63,   63,   63,   76,   76,   76,
       76,   76,   76,   63,   63,   63,   63,   63,   63,   66,
      162,   66,   66,   66,   66,   66,   66,   78,  161,   78,
       78,   78,   78,   78,   83,  159,   83,   83,   83,   83,
       83,   83,   87,   87,   87,   87,   87,   87,   88,  151,
       88,   88,   88,   88,   88,   88,   88,   88,   88,   88,
       88,   88,  102,  102,  102,  102,  102,  102,   88,   88,
       88,   88,   88,   88,   89,  150,   89,   89,   89,   89,
       89,   89,  100,  148,  100,  100,  100,  100,  100,  100,
      103,  103,  103,  103,  103,  103,  105,  147,  105,  105,

      105,  105,  105,  109,  146,  109,  109,  109,  109,  109,
      109,  119,  119,  119,  119,  119,  119,  121,  144,  121,
      121,  121,  121,  121,  124,  143,  124,  124,  124,  124,
      124,  124,  126,  126,  126,  126,  126,  126,  128,  141,
      128,  128,  128,  128,  128,  137,  137,  137,  137,  137,
      137,  138,  138,  138,  138,  138,  138,  139,  139,  139,
      139,  139,  139,  140,  140,  140,  140,  140,  140,  142,
      136,  142,  142,  142,  142,  142,  145,  135,  145,  145,
      145,  145,  145,  145,  152,  152,  152,  152,  152,  152,
      153,  153,  153,  153,  153,  155,  155,  155,  155,  155,

      155,  156,  156,  156,  156,  156,  156,  157,  157,  157,
      157,  157,  157,  158,  158,  158,  158,  158,  158,  160,
      132,  160,  160,  160,  160,  160,  166,  166,  166,  166,
      166,  166,  167,  167,  167,  167,  167,  169,  169,  169,
      169,  169,  169,  170,  170,  170,  170,  170,  170,  171,
      171,  171,  171,  171,  171,  177,  177,  177,  177,  177,
      177,  178,  178,  178,  178,  178,  194,  131,  194,  194,
      194,  194,  194,  195,  195,  195,  196,  130,  196,  129,
      196,  197,  127,  197,  198,  198,  198,  199,  199,  200,
      200,  201,  201,  202,  202,  203,  203,  204,  204,  204,

      204,  205,  205,  206,  206,  207,  207,  208,  208,  209,
      209,  210,  210,  211,  211,  212,  212,  125,  123,  122,
      120,  118,  117,  115,  114,  113,  110,  108,  107,  106,
      104,  101,   99,   98,   97,   96,   95,   94,   93,   92,
       91,   84,   82,   81,   80,   79,   77,   73,   69,   68,
       67,   62,   61,   56,   50,   48,   47,   46,   45,   44,
       43,   42,   41,   40,   39,   32,   23,   20,   19,   17,
       16,   15,    5,    3,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,

      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193,  193,  193,  193,  193,  193,  193,  193,  193,  193,
      193
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int prsa_flex_debug;
int prsa_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *prsatext;
#line 1 "prsa_tok.l"
/*	$NetBSD: prsa_tok.l,v 1.4 2006/09/09 16:22:10 manu Exp $	*/
/* Id: prsa_tok.l,v 1.2 2004/07/12 20:43:51 ludvigm Exp */
#line 6 "prsa_tok.l"
/*
 * Copyright (C) 2004 SuSE Linux AG, Nuernberg, Germany.
 * Contributed by: Michal Ludvig <mludvig@suse.cz>, SUSE Labs
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. Neither the name of the project nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/* This file contains a tokeniser for FreeS/WAN-style ipsec.secrets RSA keys. */

#include <string.h>
#include <openssl/bn.h>
#include <openssl/rsa.h>
#include "prsa_par.h"

extern int prsalex (void);
extern int prsa_cur_lineno;

#line 742 "prsa_tok.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int prsalex_destroy (void );

int prsaget_debug (void );

void prsaset_debug (int debug_flag  );

YY_EXTRA_TYPE prsaget_extra (void );

void prsaset_extra (YY_EXTRA_TYPE user_defined  );

FILE *prsaget_in (void );

void prsaset_in  (FILE * in_str  );

FILE *prsaget_out (void );

void prsaset_out  (FILE * out_str  );

yy_size_t prsaget_leng (void );

char *prsaget_text (void );

int prsaget_lineno (void );

void prsaset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int prsawrap (void );
#else
extern int prsawrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( prsatext, prsaleng, 1, prsaout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( prsain )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( prsain ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, prsain))==0 && ferror(prsain)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(prsain); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int prsalex (void);

#define YY_DECL int prsalex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after prsatext and prsaleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 56 "prsa_tok.l"

#line 926 "prsa_tok.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! prsain )
			prsain = stdin;

		if ( ! prsaout )
			prsaout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			prsaensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				prsa_create_buffer(prsain,YY_BUF_SIZE );
		}

		prsa_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of prsatext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 194 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 675 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 57 "prsa_tok.l"
{ return OBRACE; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 58 "prsa_tok.l"
{ return EBRACE; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 59 "prsa_tok.l"
{ return COLON; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 60 "prsa_tok.l"
{ return TAG_RSA; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 61 "prsa_tok.l"
{ return TAG_PSK; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 62 "prsa_tok.l"
{ return TAG_PUB; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 63 "prsa_tok.l"
{ 
			BIGNUM *bn = BN_new();
			BN_hex2bn(&bn, prsatext+2);
			prsalval.bn = bn;
			return HEX;
		}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 69 "prsa_tok.l"
{
			prsalval.chr = strdup(prsatext);
			return BASE64;
		}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 73 "prsa_tok.l"
{ return MODULUS; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 74 "prsa_tok.l"
{ return PUBLIC_EXPONENT; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 75 "prsa_tok.l"
{ return PRIVATE_EXPONENT; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "prsa_tok.l"
{ return PRIME1; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 77 "prsa_tok.l"
{ return PRIME2; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "prsa_tok.l"
{ return EXPONENT1; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 79 "prsa_tok.l"
{ return EXPONENT2; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 80 "prsa_tok.l"
{ return COEFFICIENT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 81 "prsa_tok.l"
{ return SLASH; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 82 "prsa_tok.l"
{ prsalval.num = atol(prsatext); return NUMBER; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 83 "prsa_tok.l"
{ return ADDRANY; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 84 "prsa_tok.l"
{ prsalval.chr = strdup(prsatext); return ADDR4; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 85 "prsa_tok.l"
{ prsalval.chr = strdup(prsatext); return ADDR6; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 86 "prsa_tok.l"
;
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 87 "prsa_tok.l"
{ prsa_cur_lineno++; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 88 "prsa_tok.l"
;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 89 "prsa_tok.l"
ECHO;
	YY_BREAK
#line 1143 "prsa_tok.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed prsain at a new source and called
			 * prsalex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = prsain;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( prsawrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * prsatext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of prsalex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					prsarealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			prsarestart(prsain  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) prsarealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 194 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 194 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 193);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up prsatext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					prsarestart(prsain );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( prsawrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve prsatext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void prsarestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        prsaensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            prsa_create_buffer(prsain,YY_BUF_SIZE );
	}

	prsa_init_buffer(YY_CURRENT_BUFFER,input_file );
	prsa_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void prsa_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		prsapop_buffer_state();
	 *		prsapush_buffer_state(new_buffer);
     */
	prsaensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	prsa_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (prsawrap()) processing, but the only time this flag
	 * is looked at is after prsawrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void prsa_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	prsain = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE prsa_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) prsaalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in prsa_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) prsaalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in prsa_create_buffer()" );

	b->yy_is_our_buffer = 1;

	prsa_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with prsa_create_buffer()
 * 
 */
    void prsa_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		prsafree((void *) b->yy_ch_buf  );

	prsafree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a prsarestart() or at EOF.
 */
    static void prsa_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	prsa_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then prsa_init_buffer was _probably_
     * called from prsarestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void prsa_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		prsa_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void prsapush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	prsaensure_buffer_stack();

	/* This block is copied from prsa_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from prsa_switch_to_buffer. */
	prsa_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void prsapop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	prsa_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		prsa_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void prsaensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)prsaalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in prsaensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)prsarealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in prsaensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE prsa_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) prsaalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in prsa_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	prsa_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to prsalex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       prsa_scan_bytes() instead.
 */
YY_BUFFER_STATE prsa_scan_string (yyconst char * yystr )
{
    
	return prsa_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to prsalex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE prsa_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) prsaalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in prsa_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = prsa_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in prsa_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up prsatext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		prsatext[prsaleng] = (yy_hold_char); \
		(yy_c_buf_p) = prsatext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		prsaleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int prsaget_lineno  (void)
{
        
    return prsalineno;
}

/** Get the input stream.
 * 
 */
FILE *prsaget_in  (void)
{
        return prsain;
}

/** Get the output stream.
 * 
 */
FILE *prsaget_out  (void)
{
        return prsaout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t prsaget_leng  (void)
{
        return prsaleng;
}

/** Get the current token.
 * 
 */

char *prsaget_text  (void)
{
        return prsatext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void prsaset_lineno (int  line_number )
{
    
    prsalineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see prsa_switch_to_buffer
 */
void prsaset_in (FILE *  in_str )
{
        prsain = in_str ;
}

void prsaset_out (FILE *  out_str )
{
        prsaout = out_str ;
}

int prsaget_debug  (void)
{
        return prsa_flex_debug;
}

void prsaset_debug (int  bdebug )
{
        prsa_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from prsalex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    prsain = stdin;
    prsaout = stdout;
#else
    prsain = (FILE *) 0;
    prsaout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * prsalex_init()
     */
    return 0;
}

/* prsalex_destroy is for both reentrant and non-reentrant scanners. */
int prsalex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		prsa_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		prsapop_buffer_state();
	}

	/* Destroy the stack itself. */
	prsafree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * prsalex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *prsaalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *prsarealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void prsafree (void * ptr )
{
	free( (char *) ptr );	/* see prsarealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 89 "prsa_tok.l"



