#!/bin/sh
SP="/etc/init.d/"
${SP}S26pdnsd stop
${SP}S27obssh stop
${SP}S17shadowsocks stop
${SP}S19redsocks stop
cd /etc/dnsmasq/custom
rm -f my.cfg gfwlist.cfg whitelist.cfg gfwlist_add.cfg tunlr.cfg
#cd /etc/dnsmasq/tunlr
#rm -f domains.txt
#touch domains.txt
service dnsmasq restart
cd /etc/config
mv -f tow-hyzoom.fire tow-hyzoom.tmp && service firewall restart && mv -f tow-hyzoom.tmp tow-hyzoom.fire
