#!/bin/sh
TOP=/raid1/tomato/tomato.git/release.ar.wp.chs/src-rt/router
CONFIGURE="./configure"
CC=mipsel-linux-gcc
CXX=mipsel-linux-g++
AR=mipsel-linux-ar
RANLIB=mipsel-linux-ranlib

CC=$CC CXX=$CXX AR=$AR RANLIB=$RANLIB STRIP='mipsel-uclibc-strip' HOST=mipsel-linux \
	CFLAGS="-O2 -Wall -fno-delete-null-pointer-checks -funit-at-a-time \
	--param large-function-growth=800 --param max-inline-insns-single=3000 \
	-ffunction-sections -fdata-sections" \
	LDFLAGS="-L$TOP/openssl -L$TOP/zlib -ffunction-sections -fdata-sections -Wl,--gc-sections -fPIC" \
	CPPFLAGS="-I$TOP/openssl/include -I$TOP/zlib" \
	LIBS="-lssl -lcrypto -lz" \
	$CONFIGURE --host=mipsel-linux --build=x86_64-linux-gnu  --host=mipsel-linux --disable-debug --with-libiconv-prefix=$TOP/libiconv --with-ssl=openssl

make
