#!/bin/sh
[ $# -eq 0 ] && { echo "Usage: $0 domain [rs]"; exit 1; }

ipset_add_file="/etc/dnsmasq/custom/gfwlist_add.cfg"
ipset_gfwlist_file="/etc/dnsmasq/custom/gfwlist.cfg"

if [ -n "$1" ]; then
    check_dup=$(grep "ipset=/$1" $ipset_add_file)
    check_dup_g=$(grep "ipset=/$1" $ipset_gfwlist_file)
fi

if [ -n "$check_dup" ]; then
    echo "$1 already in $ipset_add_file"
elif [ -n "$check_dup_g" ]; then
    echo "$1 already in  $ipset_gfwlist_file"
else
    echo "$1 not found in gfwlist file!"
fi
