#!/bin/sh
#Script to resetting some script..

if [ $# -lt 1 ] || [ $# -gt 3 ]; then
    echo "Usage: $0 {ss|redir|gae|ssh|off} for all subnet."
    echo "Specified IP range example: ipt redir 30 50 "
    exit 1
fi

CPATH="/etc/config/"
FNAME="tow-hyzoom"
#FNAME="`hostname`-`domainname`"
cd /etc/config
OFNAME="`ls *.fire`"
OWNAME="`ls *.wanup`"

[ ! -e "${CPATH}${FNAME}.fire" ] && mv -f "${CPATH}${OFNAME}" \
"${CPATH}${FNAME}".fire

[ ! -e "${CPATH}${FNAME}.wanup" ] && mv -f "${CPATH}${OWNAME}" \
"${CPATH}${FNAME}".wanup

ipt_para="$1"
[ -n "$2" ] && ipt_para="$1 $2"
[ -n "$3" ] && ipt_para="$1 $2 $3"
sed -i -n '/^\#iptstart/{p;:a;n;H;/^\#iptend/!ba;x;s/.*/'"ipt ${ipt_para}"'/;G;};p' \
 "${CPATH}${FNAME}.fire"

service firewall restart
