'\" t
.\"     Title: tripplite
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 04/17/2015
.\"    Manual: NUT Manual
.\"    Source: Network UPS Tools 2.7.3
.\"  Language: English
.\"
.TH "TRIPPLITE" "8" "04/17/2015" "Network UPS Tools 2\&.7\&.3" "NUT Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
tripplite \- Driver for Tripp\-Lite SmartPro UPS equipment
.SH "NOTE"
.sp
This man page only documents the hardware\-specific features of the tripplite driver\&. For information about the core driver, see \fBnutupsdrv\fR(8)\&.
.SH "SUPPORTED HARDWARE"
.sp
This driver should work on the SmartPro line, including the SMART700 and SMART700SER\&. It only supports SmartPro models that communicate using the serial port\&.
.SH "EXTRA ARGUMENTS"
.sp
This driver supports the following optional settings in the \fBups.conf\fR(5):
.PP
\fBoffdelay\fR=\fInum\fR
.RS 4
Time to wait before the UPS is turned off after the kill power command is sent\&. The default value is 64 (in seconds)\&.
.RE
.PP
\fBrebootdelay\fR=\fInum\fR
.RS 4
Set the timer before the UPS is cycled after the reboot command is sent\&. The default value is 64 (in seconds)\&.
.RE
.PP
\fBstartdelay\fR=\fInum\fR
.RS 4
Set the time that the UPS waits before it turns itself back on after a reboot command\&. The default value is 60 (in seconds)\&.
.RE
.SH "KNOWN ISSUES AND BUGS"
.sp
Battery charge information may not be correct for all UPSes\&. It is tuned to be correct for a SMART700SER\&. Other models may not provide correct information\&. Information from the manufacturer would be helpful\&.
.SH "AUTHORS"
.sp
Rickard E\&. (Rik) Faith, Nicholas Kain
.SH "SEE ALSO"
.SS "The core driver:"
.sp
\fBnutupsdrv\fR(8)
.SS "Other drivers for Tripp\-Lite hardware:"
.sp
\fBtripplitesu\fR(8), \fBtripplite_usb\fR(8), \fBusbhid-ups\fR(8)
.SS "Internet resources:"
.sp
The NUT (Network UPS Tools) home page: http://www\&.networkupstools\&.org/
