#!/bin/sh

# directory definitions
NUT_DIR="/usr"
INSTALLPATH=$NUT_DIR/script
CONFIGPATH=/etc/rc.config.d
SCRIPTPATH=/sbin/init.d
LINKPATH=/sbin/rc3.d
LINKPREFIX=991
OWNER=root
GROUP=root
SCRIPTS="nut-upsd.sh nut-drvctl.sh nut-upsmon.sh"
CONFIGS="nut-drvctl nut-upsd nut-upsmon"

SCRIPTPERMS=0744
CONFIGPERMS=0444

# make sure the nut user exists and has correct memberships
res=`grget -n nut`
if [ -z "$res" ]; then
	groupadd nut
fi
res=`pwget -n nut`
if [ -z "$res" ]; then
	useradd -g nut -G root -d ${NUT_DIR}/bin nut
fi

# make sure that conffiles are secured and have the correct ownerships
if [ -d /usr/local/nut ] ; then
        chown root:nut /usr/local/nut
fi
for file in nut.conf ups.conf upsd.conf upsmon.conf upsd.users upssched.conf; do
        if [ -f /usr/local/nut/$file ] ; then
                chown root:nut /usr/local/nut/$file
                chmod 640 /usr/local/nut/$file
        fi
done

# make sure that /var/run/nut exists and has the correct ownerships
if [ ! -d /var/run/nut ] ; then
        mkdir -p /var/run/nut
fi
if [ -d /var/run/nut ] ; then
        chown root:nut /var/run/nut
        chmod 770 /var/run/nut
fi

# make sure that /var/state/ups exists and has the correct ownerships
if [ ! -d /var/state/ups ] ; then
        mkdir -p /var/state/ups
fi
if [ -d /var/state/ups ] ; then
        chown root:nut /var/state/ups
        chmod 770 /var/state/ups
fi

#Set-up automatic start-up

if [ ! -d $CONFIGPATH ]; then
	echo "NO $CONFIGPATH"; exit 1;
fi
if [ ! -d $SCRIPTPATH ]; then
	echo "NO $SCRIPTPATH"; exit 1;
fi
if [ ! -d $LINKPATH ]; then
	echo "NO $LINKPATH"; exit 1;
fi
for script in $SCRIPTS; do
	name=`basename ${script} .sh` ;
	cp $INSTALLPATH/$script $SCRIPTPATH/$name
	chown $OWNER:$GROUP $SCRIPTPATH/$name
	chmod $SCRIPTPERMS $SCRIPTPATH/$name
	
	ln -f -s $SCRIPTPATH/$name $LINKPATH/K$LINKPREFIX$name
	ln -f -s $SCRIPTPATH/$name $LINKPATH/S$LINKPREFIX$name
done
for config in $CONFIGS; do
	cp $INSTALLPATH/$config $CONFIGPATH
	chown $OWNER:$GROUP $CONFIGPATH
	chmod $CONFIGPERMS $CONFIGPATH
done
