#!/bin/sh
TOP=/raid1/tomato/tomato.git/release.ar.wp.chs/src-rt/router
CONFIGURE="./configure"
CC=mipsel-linux-gcc
CXX=mipsel-linux-gcc

CC=$CC CXX=$CXX STRIP='mipsel-uclibc-strip' \
	CFLAGS="-O3 -Wall -fno-delete-null-pointer-checks -funit-at-a-time \
	--param large-function-growth=800 --param max-inline-insns-single=3000 \
	-ffunction-sections -fdata-sections" \
	$CONFIGURE --host=mipsel-linux --build=x86_64-linux-gnu --target=mipsel-linux --prefix=/usr --enable-shared
