#!/bin/sh
BIN=redsocks2
BINPATH="/usr/bin/"
RUN_D="/var/run"
PID_F="${RUN_D}/${BIN}.pid"
CONF="-c /etc/redsocks.conf -p ${PID_F}"
alias elog="logger -t $BIN -s"
COND=$1
[ $# -eq 0 ] && COND="start"

case $COND in
stop)
  elog "Stopping $BIN... "
  [ -n "`pidof $BIN`" ] && killall $BIN
  elog "$BIN Stopped. "
  ;;
start)
  elog "Starting $BIN... "
  [ ! -d $RUN_D ] && mkdir -p $RUN_D
  [ -n "`pidof $BIN`" ] && elog "${BIN} already running!" \
  || ${BINPATH}${BIN} $CONF &
  elog "$BIN Started. "
  ;;
restart)
  elog "Restarting $BIN... "
  [ -n "`pidof $BIN`" ] && killall $BIN
  [ ! -d $RUN_D ] && mkdir -p $RUN_D
  ${BINPATH}${BIN} $CONF &
  elog "$BIN Restart Success. "
  ;;
*)
  elog "Usage: $0 (start|stop|restart)"
  exit 1
esac
